### ISSUE TITLE
关于无法在REAMDME.md直接找到此仓库的问题

### ISSUE THREAD

**Issue by OldGodShen** [hooozen/WE-theme-Timer#3]
![image](https://user-images.githubusercontent.com/57306382/147761239-42e43e9b-1633-4e0e-bae7-6aad8b375a02.png)
建议在这里加个此仓库的链接，不然只能通过https://github.com/hooozen/hexo-theme-academic找到作者再从repo找回来

**Comment by hooozen** [comment]
这个 Readme 本身便在该仓库下，所以不存在从该 readme 找不到该仓库的情况。
如果跳转了其他页面，点击浏览器后退按钮即可。

**Comment by OldGodShen** [comment]
可是如果用户是用wallpaper安装的那用户只能看见这个
![image](https://user-images.githubusercontent.com/57306382/147851653-e3e5d392-351e-4c48-9444-eb46a8c57d5d.png)

**Comment by hooozen** [comment]
OK，我明白了，从资源文件里访问 README，我回头加上
