### ISSUE TITLE
为什么我在设置日期之后时间显示为NaN?

### ISSUE THREAD

**Issue by hongtaihu** [hooozen/WE-theme-Timer#4]
![EWC06`D7~JS }VS53FRW](https://github.com/user-attachments/assets/874fed1d-dcbe-4aa4-8ef2-b570f1743ac3)

![image](https://github.com/user-attachments/assets/11947350-6ce4-4aeb-825f-f8eb677a2ef7)
这是我的设置

**Comment by hooozen** [comment]
手动设置截止日期试一下

**Comment by hongtaihu** [comment]
没问题了，是我理解错用法了
